services:
  postgres:
    container_name: postgres-sql-mw
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: moneywise
      PGDATA: /var/lib/postgresql/data
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - spring-net
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-mw
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025

  angular-app:
    container_name: moneywise-ui
    image: node:21
    build:
      context: ./moneywise-ui
    ports:
      - 4200:4200  
        
networks:
  spring-net:
    driver: bridge

volumes:
  postgres:
    driver: local